//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher_recruitment_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<long> Version { get; set; }
        public int InsId { get; set; }
        public System.DateTime InsDateTime { get; set; }
        public Nullable<int> UpdId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual City City { get; set; }
    }
}
