//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher_recruitment_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.JobPostActivities = new HashSet<JobPostActivity>();
            this.JobPostSkills = new HashSet<JobPostSkill>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public int Quantity { get; set; }
        public Nullable<long> Version { get; set; }
        public int InsId { get; set; }
        public System.DateTime InsDateTime { get; set; }
        public Nullable<int> UpdId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostActivity> JobPostActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostSkill> JobPostSkills { get; set; }
    }
}
